// El glosario (Fase 5.18): los términos que la app usa sin explicarlos cada vez.
export interface Termino {
  clave: string;
  nombre: string;
  corta: string;
  larga: string;
}

/** La misma lista en inglés (Fase 5.25): el español manda; esto la traduce. */
export type TerminoEn = Pick<Termino, 'nombre' | 'corta' | 'larga'>;

export const GLOSARIO: Termino[] = [
  { clave: 'clv', nombre: 'CLV (closing line value)', corta: 'Cuánto mejor que la cuota de cierre fue la que tomaste.', larga: 'La cuota de cierre es la última antes de empezar y es la más informada. Si apostaste a 2,10 y cerró a 1,95, tu CLV es positivo: pillaste precio antes de que el mercado se moviera. A la larga, un CLV positivo sostenido es la mejor señal de que no es suerte.' },
  { clave: 'kelly', nombre: 'Kelly (fraccionado)', corta: 'Cuánto apostar según la ventaja y la cuota; aquí, un cuarto del Kelly completo.', larga: 'El criterio de Kelly maximiza el crecimiento del banco a largo plazo: fracción = (p·cuota − 1) / (cuota − 1). El Kelly completo es muy volátil y castiga cualquier error en la probabilidad, así que la política usa un cuarto (o un quinto) y además topes por partido, día y semana.' },
  { clave: 'devig', nombre: 'De-vig (quitar el margen)', corta: 'Convertir cuotas en probabilidades descontando la comisión de la casa.', larga: 'Las probabilidades implícitas de una casa suman más de 1: ese exceso es su margen. Quitarlo (de-vig) deja la probabilidad «justa» del mercado. La app usa el método de Shin cuando hay cuotas de Pinnacle y el proporcional en el resto.' },
  { clave: 'brier', nombre: 'Brier', corta: 'Error cuadrático medio de las probabilidades; 0 es perfecto, 0,25 es decir siempre 50/50.', larga: 'Para cada partido, (probabilidad dicha − lo que pasó)². Castiga tanto decir 90 % y fallar como decir 55 % cuando era obvio. La app lo calcula con la misma definición en los siete deportes para que las cifras se puedan comparar.' },
  { clave: 'ece', nombre: 'ECE (error de calibración)', corta: 'Cuánto se desvía lo dicho de lo ocurrido, por tramos de probabilidad.', larga: 'Se agrupan las predicciones en cubetas (50–60 %, 60–70 %…) y se compara la probabilidad media dicha con la frecuencia real de aciertos en cada una. El ECE es la media ponderada de esas diferencias: 2 pp significa que, de media, lo dicho se desvía dos puntos de lo que pasó.' },
  { clave: 'logloss', nombre: 'Log loss', corta: 'Penaliza la confianza mal puesta: decir 99 % y fallar cuesta muchísimo.', larga: 'Menos el logaritmo de la probabilidad que se dio al resultado real, en media. Más bajo es mejor; 0,693 es no saber nada con dos resultados y 1,099 con tres. Es la métrica que manda en los experimentos porque mide la probabilidad, no solo el acierto.' },
  { clave: 'abstencion', nombre: 'Abstención', corta: 'Cuando la capa de confianza decide NO apostar aunque haya ventaja.', larga: 'Datos pobres, predicción inestable, componentes en desacuerdo o mercado de mala calidad: cualquiera de esas cosas hace que la decisión sea «NO BET» aunque la probabilidad del modelo supere a la del mercado. Abstenerse es parte del modelo, no un fallo.' },
  { clave: 'walkforward', nombre: 'Walk-forward', corta: 'Validar prediciendo cada periodo solo con lo anterior a él.', larga: 'El modelo se evalúa en orden cronológico: para cada tramo (temporada, mes) solo puede usar lo que ya había pasado. Así no se hace trampa mirando el futuro, y los baselines (el local gana, el mercado) se calculan igual para poder compararlos.' },
  { clave: 'holdout', nombre: 'Holdout final', corta: 'Los partidos que nadie ha mirado (fútbol 2026+, NFL 2024+) hasta el examen final.', larga: 'Una porción del archivo apartada desde el principio. Ningún experimento la toca; promocionar un cambio exige medirlo ahí UNA vez. Mientras siga cerrado, todo lo nuevo se registra como experimento rechazado o como sombra.' },
  { clave: 'elo', nombre: 'Elo', corta: 'Un rating que sube al ganar y baja al perder, más cuanto más sorprendente el resultado.', larga: 'La diferencia de Elo entre dos equipos se convierte en probabilidad con una curva logística; la ventaja de campo se suma al local. Cada deporte tiene su versión (margen en la NBA, abridores en la MLB, quarterback en la NFL, superficie en el tenis).' },
  { clave: 'steam', nombre: 'Steam move', corta: 'Un movimiento rápido y sincronizado de las cuotas en varias casas.', larga: 'Cuando el consenso se mueve dos o más puntos de probabilidad en menos de una hora con varias casas a la vez, suele haber dinero informado detrás. La app lo señala como aproximación: ve precios, no volumen.' },
  { clave: 'psi', nombre: 'PSI (índice de estabilidad)', corta: 'Cuánto cambia la distribución de probabilidades dichas respecto al backtest.', larga: 'Compara, por cubetas, lo que el modelo dice en vivo con lo que decía en el backtest. Por encima de 0,25 la distribución es otra y salta la alerta de deriva, siempre con al menos 100 predicciones.' },
];

export const terminoDe = (clave: string) => GLOSARIO.find((t) => t.clave === clave) ?? null;

export const GLOSARIO_EN: Record<string, TerminoEn> = {
  clv: { nombre: 'CLV (closing line value)', corta: 'How much better than the closing odds the price you took was.', larga: 'The closing odds are the last ones before kick-off and the best informed. If you bet at 2.10 and it closed at 1.95, your CLV is positive: you got the price before the market moved. Over time, a sustained positive CLV is the best sign that it is not luck.' },
  kelly: { nombre: 'Kelly (fractional)', corta: 'How much to stake given the edge and the odds; here, a quarter of full Kelly.', larga: 'The Kelly criterion maximises long-run bankroll growth: fraction = (p·odds − 1) / (odds − 1). Full Kelly is very volatile and punishes any error in the probability, so the policy uses a quarter (or a fifth) plus caps per match, day and week.' },
  devig: { nombre: 'De-vig (removing the margin)', corta: "Turning odds into probabilities after removing the bookmaker's cut.", larga: "A bookmaker's implied probabilities add up to more than 1: the excess is its margin. Removing it (de-vig) leaves the market's \"fair\" probability. The app uses Shin's method when Pinnacle odds exist and the proportional method otherwise." },
  brier: { nombre: 'Brier', corta: 'Mean squared error of the probabilities; 0 is perfect, 0.25 is always saying 50/50.', larga: 'For each match, (stated probability − what happened)². It punishes both saying 90 % and missing and saying 55 % when it was obvious. The app computes it the same way in all seven sports so the figures are comparable.' },
  ece: { nombre: 'ECE (calibration error)', corta: 'How far what was said is from what happened, by probability band.', larga: 'Predictions are grouped into bins (50–60 %, 60–70 %…) and the mean stated probability is compared with the real hit rate in each. ECE is the weighted mean of those gaps: 2 pp means that, on average, what was said is two points off what happened.' },
  logloss: { nombre: 'Log loss', corta: 'Punishes misplaced confidence: saying 99 % and missing costs a lot.', larga: 'Minus the logarithm of the probability given to the actual outcome, averaged. Lower is better; 0.693 is knowing nothing with two outcomes and 1.099 with three. It is the metric that decides experiments because it measures the probability, not just the hit.' },
  abstencion: { nombre: 'Abstention', corta: 'When the trust layer decides NOT to bet even though there is an edge.', larga: 'Poor data, an unstable prediction, components that disagree or a low-quality market: any of these makes the decision "NO BET" even when the model probability beats the market. Abstaining is part of the model, not a failure.' },
  walkforward: { nombre: 'Walk-forward', corta: 'Validating by predicting each period only with what came before it.', larga: 'The model is evaluated in chronological order: for each slice (season, month) it can only use what had already happened. That way there is no peeking at the future, and the baselines (home wins, the market) are computed the same way so they can be compared.' },
  holdout: { nombre: 'Final holdout', corta: 'The matches nobody has looked at (football 2026+, NFL 2024+) until the final exam.', larga: 'A slice of the archive set aside from the start. No experiment touches it; promoting a change requires measuring it there ONCE. While it stays closed, everything new is recorded as a rejected experiment or as a shadow.' },
  elo: { nombre: 'Elo', corta: 'A rating that goes up when you win and down when you lose, more the more surprising the result.', larga: 'The Elo gap between two teams becomes a probability through a logistic curve; home advantage is added to the home side. Each sport has its own version (margin in the NBA, starters in MLB, quarterback in the NFL, surface in tennis).' },
  steam: { nombre: 'Steam move', corta: 'A fast, synchronised move of the odds across several bookmakers.', larga: 'When the consensus moves two or more probability points in under an hour with several bookmakers at once, there is usually informed money behind it. The app flags it as an approximation: it sees prices, not volume.' },
  psi: { nombre: 'PSI (population stability index)', corta: 'How much the distribution of stated probabilities has changed from the backtest.', larga: 'It compares, by bins, what the model says live with what it said in the backtest. Above 0.25 the distribution is a different one and the drift alert fires, always with at least 100 predictions.' },
};

/** El término en el idioma pedido (el español si falta la traducción). */
export function terminoEn(t: Termino, idioma: 'es' | 'en'): Termino {
  const en = idioma === 'en' ? GLOSARIO_EN[t.clave] : undefined;
  return en ? { ...t, ...en } : t;
}
