// EL registro de scripts (Fase 3.8): nombre, grupo y una línea. `npm run help` lo imprime y un
// test comprueba que cada script de package.json está aquí (y viceversa): un comando sin línea
// de ayuda no existe para quien no ha leído el código.
export const GRUPOS = {
  empezar: 'Empezar',
  datos: 'Datos',
  base: 'Base de datos y copias',
  cuotas: 'Cuotas y mercado',
  modelos: 'Modelos y backtests',
  estudios: 'Estudios',
  banco: 'Banco de papel, política y riesgo',
  operacion: 'Operación y diagnóstico',
  desarrollo: 'Desarrollo',
};

/** @type {Record<string, { grupo: keyof typeof GRUPOS; ayuda: string }>} */
export const SCRIPTS = {
  go: { grupo: 'empezar', ayuda: 'Un solo comando: comprueba, descarga o construye los datos y arranca' },
  setup: { grupo: 'empezar', ayuda: 'Asistente de primera puesta en marcha (.env, migraciones, datos, doctor)' },
  clave: { grupo: 'empezar', ayuda: 'Pon tu clave de The Odds API en el .env (sin eco, una sola línea) y compruébala gratis' },
  dev: { grupo: 'empezar', ayuda: 'Levanta backend y frontend a la vez (se para si ya hay otra copia abierta; -- --junto para las dos)' },
  'dev:server': { grupo: 'desarrollo', ayuda: 'Solo el backend, con recarga' },
  'dev:web': { grupo: 'desarrollo', ayuda: 'Solo el frontend (Vite)' },
  'dev:fixed': { grupo: 'desarrollo', ayuda: 'Backend y frontend en los puertos fijos (7374/7373)' },
  phone: { grupo: 'empezar', ayuda: 'Enseña la dirección para abrirla en el teléfono' },
  help: { grupo: 'empezar', ayuda: 'Esta lista' },
  demo: { grupo: 'empezar', ayuda: 'Modo demostración (partidos inventados y etiquetados) on/off' },
  auto: { grupo: 'operacion', ayuda: 'Programa la actualización automática en tu máquina' },
  ahorro: { grupo: 'cuotas', ayuda: 'Qué cuesta el refresco de cuotas y bajar la cadencia' },
  'fetch-data': { grupo: 'datos', ayuda: 'Descarga history.db ya construida (9 MB); ledger.db no se toca' },
  'fetch-flags': { grupo: 'datos', ayuda: 'Baja los SVG de las banderas (solo al añadir un país)' },
  'update-all': { grupo: 'datos', ayuda: 'Los seis deportes de una tirada (-- --skip-odds no gasta cuota)' },
  'update-data': { grupo: 'datos', ayuda: 'Tenis: histórico y cuotas (comprueba las fuentes antes de borrar)' },
  'update-data:bb': { grupo: 'datos', ayuda: 'Baloncesto: equipos, resultados, próximos y cuotas' },
  'update-data:fb': { grupo: 'datos', ayuda: 'Fútbol: resultados y cuotas, incremental (-- --rebuild reconstruye)' },
  'update-squads:fb': { grupo: 'datos', ayuda: 'Fútbol: plantillas de la Premier (FPL)' },
  'update-data:bsb': { grupo: 'datos', ayuda: 'Béisbol: resultados, abridores y cuotas' },
  'update-data:naf': { grupo: 'datos', ayuda: 'NFL: resultados, calendario y líneas' },
  'update-results': { grupo: 'datos', ayuda: 'Resultados de los cinco deportes de equipo, sin cuota' },
  seed: { grupo: 'datos', ayuda: 'Tenis: dataset de demostración' },
  'seed:bb': { grupo: 'datos', ayuda: 'Baloncesto: dataset de demostración' },
  'seed:experiments': { grupo: 'estudios', ayuda: 'Siembra el registro de experimentos' },
  clubelo: { grupo: 'datos', ayuda: 'Elo de ClubElo como baseline externo (-- --desde YYYY-MM-DD)' },
  bullpen: { grupo: 'datos', ayuda: 'Carga del bullpen MLB de los boxscores recientes' },
  'verify:data': { grupo: 'operacion', ayuda: 'Comprobaciones de la base (500+); falla si algo no cuadra' },
  'verify:bsb': { grupo: 'operacion', ayuda: 'Béisbol: verifica el parser contra los game logs' },
  'check-publishable': { grupo: 'operacion', ayuda: 'Que la base a publicar no lleve nada personal' },
  audit: { grupo: 'operacion', ayuda: 'Auditoría del estado de los datos' },
  doctor: { grupo: 'operacion', ayuda: 'Diagnóstico de punta a punta (-- --probar gasta 1 crédito por deporte)' },
  jobs: { grupo: 'operacion', ayuda: 'Los trabajos programados del servidor: cadencia, última ejecución, estado' },
  export: { grupo: 'operacion', ayuda: 'Exporta predicciones, apuestas, papel, snapshots o benchmark (CSV/JSON)' },
  latency: { grupo: 'operacion', ayuda: 'La latencia del escáner de líneas, por etapa' },
  tokens: { grupo: 'operacion', ayuda: 'Tokens gastados por el asistente' },
  news: { grupo: 'datos', ayuda: 'El pipeline de noticias (-- --text "…")' },
  'db:migrate': { grupo: 'base', ayuda: 'Parte tennis.db en history.db + ledger.db y aplica migraciones' },
  'db:export-history': { grupo: 'base', ayuda: 'Copia limpia de history.db para publicar' },
  'db:explain': { grupo: 'base', ayuda: 'EXPLAIN QUERY PLAN de las consultas calientes' },
  backup: { grupo: 'base', ayuda: 'Copia del libro mayor (local y S3 si hay BACKUP_S3_*)' },
  restore: { grupo: 'base', ayuda: 'Restaura una copia del libro mayor (-- <fichero>)' },
  'odds:retention': { grupo: 'base', ayuda: 'Adelgaza snapshots viejos exportándolos antes (-- --dias N --confirmar)' },
  odds: { grupo: 'cuotas', ayuda: 'Refresca las cuotas reales ahora (gasta cuota)' },
  backtest: { grupo: 'modelos', ayuda: 'Tenis: mide el modelo' },
  'backtest:bb': { grupo: 'modelos', ayuda: 'Baloncesto: mide el modelo' },
  'backtest:fb': { grupo: 'modelos', ayuda: 'Fútbol: mide el modelo (con CLV histórico y ClubElo)' },
  'backtest:bsb': { grupo: 'modelos', ayuda: 'Béisbol: mide el modelo' },
  'backtest:naf': { grupo: 'modelos', ayuda: 'NFL: mide el modelo contra el mercado' },
  'benchmark:report': { grupo: 'modelos', ayuda: 'Modelo · baselines · mercado, los cinco deportes' },
  'model:report': { grupo: 'modelos', ayuda: 'Ficha de cada modelo' },
  'model:history': { grupo: 'modelos', ayuda: 'Evolución de los modelos' },
  'shadow:report': { grupo: 'modelos', ayuda: 'Los modelos sombra contra el campeón' },
  reproduce: { grupo: 'modelos', ayuda: 'Reproduce una predicción registrada' },
  experiments: { grupo: 'estudios', ayuda: 'El registro de experimentos' },
  study: { grupo: 'estudios', ayuda: 'Un estudio por nombre (-- --list los enumera)' },
  'study:ht': { grupo: 'estudios', ayuda: 'Alias de study -- ht' },
  'study:ht-val': { grupo: 'estudios', ayuda: 'Alias de study -- ht-val' },
  'study:sigma': { grupo: 'estudios', ayuda: 'Alias de study -- sigma' },
  'study:devig': { grupo: 'estudios', ayuda: 'Alias de study -- devig' },
  'study:features': { grupo: 'estudios', ayuda: 'Alias de study -- features' },
  'study:baselines': { grupo: 'estudios', ayuda: 'Alias de study -- baselines' },
  'study:calibration': { grupo: 'estudios', ayuda: 'Alias de study -- calibration' },
  'study:dc': { grupo: 'estudios', ayuda: 'Alias de study -- dc' },
  'study:postprocess': { grupo: 'estudios', ayuda: 'Alias de study -- postprocess' },
  'study:thin': { grupo: 'estudios', ayuda: 'Alias de study -- thin' },
  'study:correlation': { grupo: 'estudios', ayuda: 'Alias de study -- correlation' },
  'study:live': { grupo: 'estudios', ayuda: 'Alias de study -- live' },
  'study:points': { grupo: 'estudios', ayuda: 'Alias de study -- points' },
  'study:ablation': { grupo: 'estudios', ayuda: 'Alias de study -- ablation' },
  'study:home-elo': { grupo: 'estudios', ayuda: 'Alias de study -- home-elo' },
  'study:home-bb': { grupo: 'estudios', ayuda: 'Alias de study -- home-bb' },
  'study:nfl-spread': { grupo: 'estudios', ayuda: 'Alias de study -- nfl-spread' },
  'study:params-bb': { grupo: 'estudios', ayuda: 'Alias de study -- params-bb' },
  'study:params-bsb': { grupo: 'estudios', ayuda: 'Alias de study -- params-bsb' },
  paper: { grupo: 'banco', ayuda: 'El banco de papel: liquida, evalúa y apuesta lo que apruebe la política' },
  staking: { grupo: 'banco', ayuda: 'La capa de decisión sobre los partidos de ahora' },
  policy: { grupo: 'banco', ayuda: 'La política versionada: show | set grupo.clave=valor --nota "…"' },
  'totp:secreto': { grupo: 'operacion', ayuda: 'Genera un secreto TOTP para el segundo factor' },
  'vapid:generar': { grupo: 'operacion', ayuda: 'Genera las claves VAPID para Web Push' },
  'secret-scan': { grupo: 'desarrollo', ayuda: 'Escáner de secretos sobre los ficheros rastreados' },
  deploy: { grupo: 'operacion', ayuda: 'Despliega en Fly.io' },
  test: { grupo: 'desarrollo', ayuda: 'Tests del servidor' },
  e2e: { grupo: 'desarrollo', ayuda: 'Humo de punta a punta con Playwright (tras npm run build)' },
  'update-data:nhl': { grupo: 'datos', ayuda: 'NHL: resultados (sportsdataverse en GitHub; --fuente nhl para api-web.nhle.com; --desde, --hasta), calendario y, con clave, cuotas (--skip-odds)' },
  'backtest:nhl': { grupo: 'modelos', ayuda: 'NHL: Elo + Poisson contra dos referencias, sin el holdout (2025-26 en adelante); escribe calibración y walk-forward; --ajustar --registrar' },
  'update-data:ufc': { grupo: 'datos', ayuda: 'UFC: el archivo de ufcstats (Greco1899/scrape_ufc_stats en GitHub) y, con clave, las peleas que vienen con sus cuotas (--skip-odds)' },
  'backtest:ufc': { grupo: 'modelos', ayuda: 'UFC: el modelo publicado (logística Elo + récord + ficha, walk-forward) sin el holdout (2026 →); escribe calibración y walk-forward; --combinado / --ajustar --registrar' },
  carga: { grupo: 'desarrollo', ayuda: 'Prueba de carga: p50/p95 de los endpoints de predicciones y 50 conexiones SSE (servidor en marcha; --url para otro)' },
  'carga:ci': { grupo: 'desarrollo', ayuda: 'La prueba de carga contra la base de demostración, fallando si algo pasa de config/presupuestos.json (tras npm run build)' },
  build: { grupo: 'desarrollo', ayuda: 'Build del frontend + typecheck del backend' },
  typecheck: { grupo: 'desarrollo', ayuda: 'Tipos de los dos workspaces' },
  lint: { grupo: 'desarrollo', ayuda: 'oxlint' },
  prepare: { grupo: 'desarrollo', ayuda: '(npm) activa el hook de pre-commit' },
};
